spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/blogproject
    username: sa
    password: tt
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update #후에는 update로 변경
    properties:
      hibernate:
  # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace
